import{a as u,i as n,S as g}from"./assets/vendor-b2578120.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function l(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=l(t);fetch(t.href,r)}})();async function f(e,s){const o="https://pixabay.com/api/",t={key:"43018302-cdfd5f670eb7813c2554bba0c",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:s};return(await u.get(o,{params:t})).data}function h(e){return`<li class="gallery-item">
            <a class="image-link" href="${e.largeImageURL}">
            <img loading="lazy" class="image" src="${e.webformatURL}" alt="${e.tags}"/>
            </a>
            <ul class="list-container">
            <li class="item-container"><p><span class="title">Likes</span></br>${e.likes}</p></li>
            <li class="item-container"><p><span class="title">Views</span></br>${e.views}</p></li>
            <li class="item-container"><p><span class="title">Comments</span></br>${e.comments}</p></li>
            <li class="item-container"><p><span class="title">Downloads</span></br>${e.downloads}</p></li>
            </ul>
            </li>`}function y(e){return e.map(h).join()}function F(e){const s=y(e);if(e.length==0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});return}else d.insertAdjacentHTML("beforeend",s);L.refresh()}const c=document.querySelector(".search-form"),d=document.querySelector(".gallery");document.querySelector(".js-btn-load");const m=document.querySelector(".loader");let i,p=1;const L=new g(".gallery a",{captionDelay:250,captionsData:"alt"});c.addEventListener("submit",async e=>{e.preventDefault(),i=e.target.elements.query.value.trim(),d.innerHTML="",p=1,i||n.show({message:"Please complete the field!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});try{w();const s=await f(i,p);F(s.hits)}catch(s){console.log(s),n.error({message:"Sorry, an error occurred while loading. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}b(),c.reset()});const w=()=>{m.classList.remove("hidden")},b=()=>{m.classList.add("hidden")};
//# sourceMappingURL=commonHelpers.js.map
