import{a as m,i as n,S as d}from"./assets/vendor-b2578120.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();async function f(o){const r="https://pixabay.com/api/",a={key:"43018302-cdfd5f670eb7813c2554bba0c",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0};return(await m.get(r,{params:a})).data}function g(o){if(o.length==0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});return}else{const s=o.map(r=>`<li class="gallery-item">
            <a class="image-link" href="${r.largeImageURL}">
            <img class="image" src="${r.webformatURL}" alt="${r.tags}"/>
            </a>
            <ul class="list-container">
            <li class="item-container"><p><span class="title">Likes</span></br>${r.likes}</p></li>
            <li class="item-container"><p><span class="title">Views</span></br>${r.views}</p></li>
            <li class="item-container"><p><span class="title">Comments</span></br>${r.comments}</p></li>
            <li class="item-container"><p><span class="title">Downloads</span></br>${r.downloads}</p></li>
            </ul>
            </li>`).join("");u.insertAdjacentHTML("beforeend",s),y.refresh()}}const c=document.querySelector(".search-form"),p=document.querySelector(".search-input");p.value.trim();const u=document.querySelector(".gallery"),y=new d(".gallery a",{captionDelay:250,captionsData:"alt"}),l=document.querySelector(".loader");l.style.display="none";const h=()=>{l.style.display="flex"},F=()=>{l.style.display="none"};c.addEventListener("submit",async o=>{o.preventDefault(),u.innerHTML="";const s=p.value.trim();if(s!==""){h();try{const r=await f(s);g(r.hits)}catch(r){console.log(r),n.error({message:"Sorry, an error occurred while loading. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}F(),c.reset()}else n.show({message:"Please complete the field!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})});
//# sourceMappingURL=commonHelpers.js.map
