import{a as w,S as b,i as n}from"./assets/vendor-03da8548.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function l(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=l(t);fetch(t.href,o)}})();async function m(e,r){const l="https://pixabay.com/api/",a={key:"43018302-cdfd5f670eb7813c2554bba0c",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};return(await w.get(l,{params:a})).data}const S=new b(".gallery a",{captionDelay:250,captionsData:"alt"});function v(e){return`<li class="gallery-item">
            <a class="image-link" href="${e.largeImageURL}">
            <img loading="lazy" class="image" src="${e.webformatURL}" alt="${e.tags}"/>
            </a>
            <ul class="list-container">
            <li class="item-container"><p><span class="title">Likes</span></br>${e.likes}</p></li>
            <li class="item-container"><p><span class="title">Views</span></br>${e.views}</p></li>
            <li class="item-container"><p><span class="title">Comments</span></br>${e.comments}</p></li>
            <li class="item-container"><p><span class="title">Downloads</span></br>${e.downloads}</p></li>
            </ul>
            </li>`}function P(e){return e.map(v).join("")}function h(e){const r=P(e);if(e.length==0){iziToast.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});return}else d.insertAdjacentHTML("beforeend",r);S.refresh()}const u=document.querySelector(".search-form"),d=document.querySelector(".gallery"),p=document.querySelector(".js-btn-load"),g=document.querySelector(".loader");let i,s=1,f=0;const R=15;u.addEventListener("submit",async e=>{if(e.preventDefault(),i=e.target.elements.query.value.trim(),d.innerHTML="",s=1,!i){n.show({message:"Please complete the field!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});return}try{F();const r=await m(i,s);f=Math.ceil(r.totalHits/R),h(r.hits)}catch{n.error({message:"Sorry, an error occurred while loading. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}L(),y(),u.reset()});p.addEventListener("click",async e=>{try{F(),s+=1;const r=await m(i,s);h(r.hits)}catch{n.error({message:"Sorry, an error occurred while loading. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}E(),y(),L()});function y(){s>=f?(B(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):q()}function q(){p.classList.remove("hidden")}function B(){p.classList.add("hidden")}function F(){g.classList.remove("hidden")}function L(){g.classList.add("hidden")}function E(){const e=d.firstChild.getBoundingClientRect().height;scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
